### PR TITLE
test(visual-regression): Allow container volume args to be overridden

### PR DESCRIPTION
**Pull request by jpveooys**
This updates `scripts/run-playwright-container.sh` so that an overlay file system is used when mounting the current directory (including node_modules). This means `node_modules` starts off the same as the host, but any changes written to it in the container are temporary and limited to the container itself.

The `e2e` directory is mounted normally so that reports and screenshots are written to the host.

This speeds up the `npm install` part of `npm run test:visual` for me (on Ubuntu).

@adamledwards Could you check if this works okay for you?

### CODE REVIEW

**Comment by adamledwards** [comment]
This fails for me unfortunately 
```
npm ERR! code ENOSYS
npm ERR! syscall mkdir
npm ERR! path /work/node_modules/@moduk/.frontend-VpUUEEHd
npm ERR! errno -38
npm ERR! ENOSYS: function not implemented, mkdir '/work/node_modules/@moduk/.frontend-VpUUEEHd'
```

I'll be looking at fuse-overlay to see if there is something I am missing in my setup.

**Comment by jpveooys** [comment]
Reworked this so the volume arguments are the same as they were before, but can now be overridden using an environment variable so using customised arguments is possible. (E.g. I'm using `export PLAYWRIGHT_CONTAINER_VOLUME_ARGS="-v "$(pwd)":/work/:O -v "$(pwd)/e2e/":/work/e2e/"` on Ubuntu.)

**Comment by jpveooys** [comment]
@adamledwards This should be okay for you now if you want to have another look.

**Comment by adamledwards** [comment]
will have a look this afternoon

**Comment by adamledwards** [comment]
This is working for me, I doubt it is related but hitting a issue with macro-options.spec.ts not matching the screenshot, I'll verify if this is the same for main

**Review by adamledwards — APPROVED** [review]
😎

**Pull request merged**
